Feature Student : Login, Register, Profile
Kelompok-8-alterra/LMS-Backend pull request #2
Opened 2021-12-14 09:04 UTC by ilhamtri333

Review suhu feature student : login, register, profile

2021-12-14 09:06 UTC, krisnadwipayana07 approved these changes

2021-12-14 13:28 UTC, daffaalex22 requested changes

2021-12-14 13:28 UTC, daffaalex22 commented on business/student/usecase.go
> +	if domain.Avatar == "" {
Register perlu masukkin avatar?

2021-12-14 13:28 UTC, daffaalex22 commented on business/student/usecase.go
> +	if domain.Address == "" {
address menurut guaa opsional ajaa, sama phone number. Biasa aja kek regist ke app kan yg ditanya antara email atau phone number, gak dua dua nya. Gak selalu ditanya address juga.

2021-12-16 08:57 UTC, krisnadwipayana07 requested changes

2021-12-16 08:57 UTC, krisnadwipayana07 commented on controllers/student/response/response.go
> +	Password string         `json:"password"`
password ga perlu di return, keep password secret

2021-12-17 04:57 UTC, daffaalex22 approved these changes

2021-12-17 08:03 UTC, krisnadwipayana07 approved these changes

2021-12-19 16:53 UTC, merged