feature (categories): add Get ALL categories
Kelompok-8-alterra/LMS-Backend pull request #3
Opened 2021-12-15 06:16 UTC by krisnadwipayana07

make student and teacher get all categories only

2021-12-15 07:55 UTC, daffaalex22 approved these changes

2021-12-15 16:36 UTC, daffaalex22 requested changes

2021-12-15 16:36 UTC, daffaalex22 commented on app/routes/route.go
> +	ev1.GET("/GetAll", cl.CategoryController.GetAll)
Gaperlu pake /GetAll

2021-12-16 09:52 UTC, daffaalex22 commented on controllers/categories/http.go
> +	responseCategory := []response.CategoryResponse{}
Jadiin Listfromdomain di response.go

2021-12-16 10:08 UTC, daffaalex22 approved these changes

2021-12-16 10:23 UTC, ilhamtri333 approved these changes

2021-12-16 10:23 UTC, merged