Feature/course : add Create Course
Kelompok-8-alterra/LMS-Backend pull request #4
Opened 2021-12-17 07:51 UTC by krisnadwipayana07

2021-12-17 08:38 UTC, daffaalex22 commented on controllers/courses/http.go
> +	return controllers.NewSuccesResponse(c, data)
Kurang benar

2021-12-17 08:38 UTC, daffaalex22 commented on controllers/courses/response/add.go
> +			Id:        domain.Category.Id,
Ini Ada yg salah

2021-12-20 06:14 UTC, daffaalex22 approved these changes

2021-12-20 06:57 UTC, ilhamtri333 requested changes

2021-12-20 06:57 UTC, ilhamtri333 commented on drivers/database/course/mysql.go
> +		Conn: conn,
untuk penamaan samain aja kris db, sama file folder jangan mysql.go tapi jadiin repository.go aja biar selaras

2021-12-20 07:03 UTC, krisnadwipayana07 commented on drivers/database/course/mysql.go
> +		Conn: conn,
di koneksinya tu kak?

2021-12-20 07:20 UTC, ilhamtri333 commented on drivers/database/course/mysql.go
> +		Conn: conn,
iyaa kris

2021-12-20 07:24 UTC, ilhamtri333 approved these changes

2021-12-20 07:24 UTC, merged