feature add enrollment
Kelompok-8-alterra/LMS-Backend pull request #7
Opened 2021-12-21 06:42 UTC by ilhamtri333

fix error dan add enroll : penampakan
![image](https://user-images.githubusercontent.com/74149436/146883721-f3ce828e-f1ca-4062-bcbf-1be8c32e3bbb.png)

2021-12-21 08:54 UTC, krisnadwipayana07 requested changes

2021-12-21 08:54 UTC, krisnadwipayana07 commented on controllers/enrollments/request/request.go
> +	Course_Id  uint `json:"courseid"`
yang ini penamaannya kak, mungkin pakek camel case soalnya biar selaras kak wkwk, jadi nanti gampang di frontendnya

2021-12-21 08:54 UTC, krisnadwipayana07 commented on controllers/enrollments/response/response.go
> +	Course_Id  uint                            `json:"courseid"`
ini camel case responnya, biar selaras sama createdAt

2021-12-22 04:22 UTC, daffaalex22 commented on drivers/database/enrollments/repository.go
> +	checkStudent := repo.db.Table("students").Where("id = ?", newEnroll.StudentId).Find(&newEnroll.Student)
pindah ke useccase

2021-12-22 04:22 UTC, daffaalex22 commented on drivers/database/enrollments/repository.go
> +	checkCourse := repo.db.Table("courses").Where("id = ?", newEnroll.CourseId).Find(&newEnroll.Course)
pindah ke usecase

2021-12-24 06:35 UTC, krisnadwipayana07 approved these changes

2021-12-24 09:14 UTC, daffaalex22 approved these changes

2021-12-24 09:19 UTC, merged