feature(course): add update data course
Kelompok-8-alterra/LMS-Backend pull request #8
Opened 2021-12-21 08:16 UTC by krisnadwipayana07

## Preview Result
### Sucesss
![image](https://user-images.githubusercontent.com/72346645/146894713-0993af49-faaf-4a6e-8202-fdad8dfc2ade.png)

### Error Request
![image](https://user-images.githubusercontent.com/72346645/146895068-faacca2c-2804-42d1-85be-6c335bcd7d91.png)

2021-12-21 09:42 UTC, krisnadwipayana07 commented on drivers/database/course/repository.go
> +	newCourse.UpdatedAt = time.Now()
update at automation

2021-12-21 09:42 UTC, krisnadwipayana07 commented on drivers/database/course/repository.go
> +	}
Pindah ke Use case checking

2021-12-22 04:11 UTC, daffaalex22 commented on drivers/database/course/repository.go
> +	checkCourse := rep.DB.Where("id = ?", newCourse.Id).Find(&targetTable)
Ini bikin fungsi di usecase

2021-12-22 04:11 UTC, daffaalex22 commented on drivers/database/course/repository.go
> +	checkCategories := rep.DB.Table("categories").Where("id = ?", newCourse.CategoryId).Find(&newCourse.Category)
bikin fungsi di usecase

2021-12-22 04:11 UTC, daffaalex22 commented on drivers/database/course/repository.go
> +	checkTeacher := rep.DB.Table("teachers").Where("id = ?", newCourse.TeacherId).Find(&newCourse.Teacher)
bikin fungsi di usecase

2021-12-22 04:23 UTC, daffaalex22 commented on helper/err/code.go
> +// func ErrorUpdateCourse(thisError error) int {
Comment byk bagusnya dihapus, gak harus

2021-12-23 13:17 UTC, ilhamtri333 approved these changes

2021-12-25 08:54 UTC, ilhamtri333 requested changes

2021-12-25 08:54 UTC, ilhamtri333 commented on business/course/usecase.go
> +	if id == "" {
ini kenapa id nya pake string?

2021-12-25 08:54 UTC, ilhamtri333 commented on business/course/usecase.go
> +	_, err1 := uc.Repo.GetCourseById(ctx, domain.Id)
kenapa cek id course lewat fungsi? saran pake repo.Find(&course, "id = ?", id)

2021-12-25 10:32 UTC, krisnadwipayana07 commented on business/course/usecase.go
> +	if id == "" {
data yang diterima di paramsnya string kak, makanya aku terima dalam bentuk string kak

2021-12-28 08:05 UTC, ilhamtri333 approved these changes

2021-12-28 10:16 UTC, ilhamtri333 approved these changes

2021-12-28 10:26 UTC, daffaalex22 approved these changes

2021-12-28 11:19 UTC, merged